service: auth-lambda-hooks

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8


custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true

package:
  exclude:
    - node_modules/**

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
